import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.OAS3Definition = {
  openapi: "3.0.0",
  info: {
    title: "Plaza API",
    version: "1.0.0",
    description:
      "Application API: jobs, quotes, invoices, clients, schedule, staff, activities, roles, integrations, and auth. Authenticate with Bearer token (UUID) or session cookie.",
  },
  servers: [{ url: "/api", description: "Base API path" }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "UUID",
        description: "API token from Integrations Center",
      },
      cookieAuth: {
        type: "apiKey",
        in: "cookie",
        name: "connect.sid",
        description: "Session cookie for web UI",
      },
    },
    schemas: {
      Client: {
        type: "object",
        description: "Client record (individual or company)",
        properties: {
          id: { type: "string", format: "uuid" },
          firstName: { type: "string" },
          lastName: { type: "string" },
          email: { type: "string", format: "email", nullable: true },
          phone: { type: "string", nullable: true },
          mobilePhone: { type: "string", nullable: true },
          company: { type: "string", nullable: true },
          entityType: { type: "string", enum: ["individual", "company"] },
          streetAddress: { type: "string", nullable: true },
          streetAddress2: { type: "string", nullable: true },
          city: { type: "string", nullable: true },
          state: { type: "string", nullable: true },
          postalCode: { type: "string", nullable: true },
          country: { type: "string", nullable: true },
          portalEnabled: { type: "boolean" },
          notes: { type: "string", nullable: true },
          isActive: { type: "boolean" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
      Quote: {
        type: "object",
        description: "Quote record (job estimate for a client)",
        properties: {
          id: { type: "string", format: "uuid" },
          quoteNumber: { type: "string", description: "Unique human-readable quote number" },
          referenceNumber: { type: "integer", nullable: true, description: "Shared ref linking quote/job/invoice" },
          clientId: { type: "string", format: "uuid", nullable: true },
          clientName: { type: "string" },
          clientEmail: { type: "string", nullable: true },
          clientPhone: { type: "string", nullable: true },
          clientAddress: { type: "string" },
          jobType: { type: "string" },
          description: { type: "string", nullable: true },
          status: { type: "string", enum: ["draft", "sent", "accepted", "rejected", "expired"] },
          clientStatus: { type: "string", enum: ["pending", "approved", "rejected", "changes_requested"], nullable: true },
          clientApprovedAt: { type: "string", format: "date-time", nullable: true },
          clientRejectedAt: { type: "string", format: "date-time", nullable: true },
          subtotal: { type: "string" },
          taxRate: { type: "string", nullable: true },
          taxAmount: { type: "string" },
          total: { type: "string" },
          validUntil: { type: "string", format: "date", nullable: true },
          notes: { type: "string", nullable: true },
          termsAndConditions: { type: "string", nullable: true },
          termsOfTradeTemplateId: { type: "string", format: "uuid", nullable: true },
          termsOfTradeContent: { type: "string", nullable: true },
          convertedToJobId: { type: "string", format: "uuid", nullable: true },
          convertedToInvoiceId: { type: "string", format: "uuid", nullable: true },
          revisionNumber: { type: "integer" },
          parentQuoteId: { type: "string", format: "uuid", nullable: true },
          revisionReason: { type: "string", nullable: true },
          isLatestRevision: { type: "boolean" },
          supersededByQuoteId: { type: "string", format: "uuid", nullable: true },
          createdById: { type: "string", format: "uuid", nullable: true },
          sentAt: { type: "string", format: "date-time", nullable: true },
          acceptedAt: { type: "string", format: "date-time", nullable: true },
          rejectedAt: { type: "string", format: "date-time", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
          updatedAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      LineItem: {
        type: "object",
        description: "Quote or invoice line item",
        properties: {
          id: { type: "string", format: "uuid" },
          quoteId: { type: "string", format: "uuid", nullable: true },
          invoiceId: { type: "string", format: "uuid", nullable: true },
          quoteMilestoneId: { type: "string", format: "uuid", nullable: true },
          heading: { type: "string", nullable: true },
          description: { type: "string" },
          richDescription: { type: "string", nullable: true },
          quantity: { type: "string" },
          unitPrice: { type: "string" },
          amount: { type: "string" },
          sortOrder: { type: "integer", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      QuoteWithLineItems: {
        allOf: [
          { $ref: "#/components/schemas/Quote" },
          {
            type: "object",
            properties: {
              lineItems: {
                type: "array",
                items: { $ref: "#/components/schemas/LineItem" },
              },
            },
          },
        ],
        description: "Quote with nested line items",
      },
      QuoteMilestone: {
        type: "object",
        description: "Quote phase/milestone for grouping line items",
        properties: {
          id: { type: "string", format: "uuid" },
          quoteId: { type: "string", format: "uuid" },
          title: { type: "string" },
          description: { type: "string", nullable: true },
          sequence: { type: "integer" },
          expectedStartDate: { type: "string", format: "date", nullable: true },
          expectedEndDate: { type: "string", format: "date", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      QuoteCustomSection: {
        type: "object",
        description: "Custom text section on a quote (e.g. What's Included)",
        properties: {
          id: { type: "string", format: "uuid" },
          quoteId: { type: "string", format: "uuid" },
          heading: { type: "string" },
          content: { type: "string" },
          sortOrder: { type: "integer", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      QuotePaymentSchedule: {
        type: "object",
        description: "Payment schedule entry (deposit, progress, final)",
        properties: {
          id: { type: "string", format: "uuid" },
          quoteId: { type: "string", format: "uuid" },
          type: { type: "string", enum: ["deposit", "progress", "final"] },
          name: { type: "string" },
          isPercentage: { type: "boolean" },
          percentage: { type: "string", nullable: true },
          fixedAmount: { type: "string", nullable: true },
          calculatedAmount: { type: "string", nullable: true },
          quoteMilestoneId: { type: "string", format: "uuid", nullable: true },
          dueDaysFromAcceptance: { type: "integer", nullable: true },
          sortOrder: { type: "integer", nullable: true },
          isPaid: { type: "boolean" },
          paidAt: { type: "string", format: "date-time", nullable: true },
          paidAmount: { type: "string", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      QuoteWorkflowEvent: {
        type: "object",
        description: "Audit event for quote (sent, viewed, approved, etc.)",
        properties: {
          id: { type: "string", format: "uuid" },
          quoteId: { type: "string", format: "uuid" },
          eventType: { type: "string" },
          actorType: { type: "string", enum: ["staff", "client"] },
          actorId: { type: "string", nullable: true },
          notes: { type: "string", nullable: true },
          metadata: { type: "object", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      TermsTemplate: {
        type: "object",
        description: "Terms of trade template",
        properties: {
          id: { type: "string", format: "uuid" },
          name: { type: "string" },
          content: { type: "string" },
          serviceType: { type: "string", nullable: true },
          isDefault: { type: "boolean" },
          createdById: { type: "string", format: "uuid", nullable: true },
          createdAt: { type: "string", format: "date-time", nullable: true },
          updatedAt: { type: "string", format: "date-time", nullable: true },
        },
      },
      ErrorMessage: {
        type: "object",
        properties: {
          message: { type: "string", description: "Error message" },
          errors: { type: "array", items: { type: "object" }, description: "Validation errors (optional)" },
        },
      },
      CreateFullQuoteRequest: {
        type: "object",
        description: "Request body for POST /quotes/full – create quote with milestones, line items, payment schedules, and custom sections in one atomic request",
        required: ["clientId", "clientName", "clientAddress", "jobType"],
        properties: {
          clientId: { type: "string", format: "uuid", description: "Client UUID" },
          clientName: { type: "string", minLength: 1 },
          clientEmail: { type: "string", nullable: true },
          clientPhone: { type: "string", nullable: true },
          clientAddress: { type: "string", minLength: 1 },
          jobType: { type: "string", description: "Job type code" },
          description: { type: "string", nullable: true },
          validUntil: { type: "string", format: "date", nullable: true },
          notes: { type: "string", nullable: true },
          taxRate: { type: "string", nullable: true },
          subtotal: { type: "string", nullable: true },
          taxAmount: { type: "string", nullable: true },
          total: { type: "string", nullable: true },
          termsOfTradeTemplateId: { type: "string", format: "uuid", nullable: true },
          termsOfTradeContent: { type: "string", nullable: true },
          milestones: {
            type: "array",
            items: {
              type: "object",
              required: ["title", "lineItem"],
              properties: {
                title: { type: "string", minLength: 1 },
                description: { type: "string", nullable: true },
                sequence: { type: "integer", nullable: true },
                lineItem: {
                  type: "object",
                  required: ["description", "unitPrice", "amount"],
                  properties: {
                    heading: { type: "string", nullable: true },
                    description: { type: "string", minLength: 1 },
                    richDescription: { type: "string", nullable: true },
                    quantity: { type: "string", nullable: true },
                    unitPrice: { type: "string" },
                    amount: { type: "string" },
                    sortOrder: { type: "integer", nullable: true },
                  },
                },
              },
            },
          },
          paymentSchedules: {
            type: "array",
            items: {
              type: "object",
              required: ["type", "name"],
              properties: {
                type: { type: "string", enum: ["deposit", "progress", "final", "milestone"] },
                name: { type: "string", minLength: 1 },
                isPercentage: { type: "boolean", nullable: true },
                percentage: { type: "string", nullable: true },
                fixedAmount: { type: "string", nullable: true },
                calculatedAmount: { type: "string", nullable: true },
                dueDaysFromAcceptance: { type: "integer", nullable: true },
                sortOrder: { type: "integer", nullable: true },
              },
            },
          },
          customSections: {
            type: "array",
            items: {
              type: "object",
              required: ["heading"],
              properties: {
                heading: { type: "string", minLength: 1 },
                content: { type: "string", nullable: true },
                sortOrder: { type: "integer", nullable: true },
              },
            },
          },
          options: {
            type: "object",
            properties: {
              status: { type: "string", enum: ["draft", "sent"] },
              sendEmail: { type: "boolean", description: "If true and status is sent, send quote email to client" },
            },
          },
        },
      },
    },
  },
  security: [{ bearerAuth: [] }, { cookieAuth: [] }],
};

/**
 * Generate OpenAPI spec from JSDoc @openapi annotations in route files.
 * Include all main app modules so jobs, quotes, invoices, clients, schedule, staff, activities, etc. appear in docs.
 */
export function generateSwaggerSpec(): Record<string, unknown> {
  const spec = swaggerJsdoc({
    definition: options,
    apis: [
      "./server/modules/integrations/routes.ts",
      "./server/modules/auth/routes.ts",
      "./server/modules/jobs/routes.ts",
      "./server/modules/quotes/routes.ts",
      "./server/modules/invoices/routes.ts",
      "./server/modules/clients/routes.ts",
      "./server/modules/schedule/routes.ts",
      "./server/modules/staff/routes.ts",
      "./server/modules/activities/routes.ts",
      "./server/modules/roles/routes.ts",
    ],
  });
  return spec as Record<string, unknown>;
}
