export {
  integrations,
  scopes,
  services,
  integrationAuditLogs,
  insertIntegrationSchema,
  insertScopeSchema,
  insertServiceSchema,
  insertIntegrationAuditLogSchema,
  integrationStatuses,
  integrationActions,
  type Integration,
  type InsertIntegration,
  type Scope,
  type InsertScope,
  type Service,
  type InsertService,
  type IntegrationAuditLog,
  type InsertIntegrationAuditLog,
} from "@shared/schema";
